gravitee-io/gravitee-common

src/main/java/io/gravitee/common/util/URIUtils.java, src/test/java/io/gravitee/common/util/URIUtilsTest.java
=> fix(uriutils): parse parameters fails if the last param is empty

src/main/java/io/gravitee/common/service/AbstractService.java
https://github.com/gravitee-io/issues/issues/6306
add AbtractService startup order
ServiceManager will start all services plugins using this order, starting with lower ones at first.
And will stop them starting with higher ones at first.
It allows to ensure services consuming SynService events are started before he produces it.
We choose the getOrder() naming as it's already use, for example in upgraders
=> fix: add AbtractService startup order

pom.xml, src/main/java/io/gravitee/common/util/VertxProxyOptionsUtils.java, src/test/java/io/gravitee/common/util/VertxProxyOptionsUtilsTest.java
Because environment is not always accessed from spring application context,
we need a way to build the vertx proxy options from other sources.
To answer that need, Vertx proxy options are created from the gravitee node `Configuration` interface.
---
- use it directly by updating your project with version: `1.26.1-fix-vertx-proxy-options-utils-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/1.26.1-fix-vertx-proxy-options-utils-SNAPSHOT/gravitee-common-1.26.1-fix-vertx-proxy-options-utils-SNAPSHOT.zip)
=> fix: init vertx proxy options from node configuration

.circleci/config.yml, pom.xml, src/main/java/io/gravitee/common/utils/RxHelper.java, src/test/java/io/gravitee/common/utils/RxHelperTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/7990
---
- use it directly by updating your project with version: `2.0.0-bumpRxJava-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/2.0.0-bumpRxJava-SNAPSHOT/gravitee-common-2.0.0-bumpRxJava-SNAPSHOT.zip)
=> Bump rx java

src/main/java/io/gravitee/common/util/KeyStoreUtils.java
**Issue**
https://github.com/gravitee-io/issues/issues/APIM-200
Use  `passwordToCharArray` everywhere it is required
---
- use it directly by updating your project with version: `2.0.0-apim-200-mqtt5-security-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/2.0.0-apim-200-mqtt5-security-SNAPSHOT/gravitee-common-2.0.0-apim-200-mqtt5-security-SNAPSHOT.zip)
=> fix: use passwordToCharArray to properly handle password

pom.xml, src/main/java/io/gravitee/common/util/URIUtils.java, src/test/java/io/gravitee/common/util/URIUtilsTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-455
Add an util function to quickly check if a url is absolute or not.
[APIM-455]: https://gravitee.atlassian.net/browse/APIM-455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- use it directly by updating your project with version: `2.1.0-apim-455-user-defined-endpoint-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/2.1.0-apim-455-user-defined-endpoint-SNAPSHOT/gravitee-common-2.1.0-apim-455-user-defined-endpoint-SNAPSHOT.zip …
=> feat: add uri isAbsolute util function

src/main/java/io/gravitee/common/utils/RxHelper.java, src/test/java/io/gravitee/common/utils/RxHelperTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-373
Add a predicate in `RxHelper#retry...()` functions to be able to retry only if the predicate is true.
The aim of that is to be able to retry only throwable that match the predicate.
---
- use it directly by updating your project with version: `2.1.0-apim-373-subscription-error-management-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/2.1.0-apim-373-subscription-error-management-SNAPSHOT/gravitee-common-2.1.0-apim-373-subscription-error-management-SNAPSHOT.zip)
=> feat: add retry on predicate capabilities

src/main/java/io/gravitee/common/utils/DurationParser.java
Remove the usage of spring framework for DurationParser.
---
- use it directly by updating your project with version: `2.1.0-fix-duration-parser-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/2.1.0-fix-duration-parser-SNAPSHOT/gravitee-common-2.1.0-fix-duration-parser-SNAPSHOT.zip)
=> fix: remove the use of Spring framework

src/main/java/io/gravitee/common/utils/DurationParser.java
**Issue**
Remove the usage of spring utils (because provided dependency) by creating a private method to deal with empty string when parsing duration.
=> fix: create private method to deal with empty string

src/main/java/io/gravitee/common/util/URIUtils.java, src/test/java/io/gravitee/common/util/URIUtilsTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-2218
---
- use it directly by updating your project with version: `2.3.0-apim-2218-semicolon-query-params-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/2.3.0-apim-2218-semicolon-query-params-SNAPSHOT/gravitee-common-2.3.0-apim-2218-semicolon-query-params-SNAPSHOT.zip)
=> feat: parse semicolon as a normal char for query parameters

src/main/java/io/gravitee/common/util/EnvironmentUtils.java, src/test/java/io/gravitee/common/util/EnvironmentUtilsTest.java
When creating a api v4, tags param could be null otherwise we didn't check this and return true even if the gateway has been setup with tags.
---
- use it directly by updating your project with version: `3.2.1-fix-has-matching-tags-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/3.2.1-fix-has-matching-tags-SNAPSHOT/gravitee-common-3.2.1-fix-has-matching-tags-SNAPSHOT.zip)
=> fix: return false when given matching tags is null or empty

pom.xml, src/main/java/io/gravitee/common/templating/FreeMarkerComponent.java, src/test/java/io/gravitee/common/templating/FreeMarkerComponentTest.java, src/test/resources/freemarker/subpackage/template.ftl, src/test/resources/freemarker/template.ftl
Both gravitee-reporter-common and gravitee-common-elasticsearch define their own FreemarkerComponent. 
The only diff between those two implementations is that one of them injects a Spring value to read templates from the FS.
One or the other of those implementation are used in:
- gravitee-reporter-common (its own implem)
- gravitee-reporter-elasticsearch (which uses the one from common-elasticsearch, but indirectly  also the one from reporter-common as it depends on it for formatting)
- gravitee-api-management (for seeding data in our elasticsearch-repository tests)
As templating capability does not really have to do with reporting or with elasticsearch, the idea of this PR is to make this utility class re-usable whatever the context is and to put it in a common place to be reused by …
=> feat: add reusable freemarker templating component

src/main/java/io/gravitee/common/util/EnvironmentUtils.java, src/test/java/io/gravitee/common/util/EnvironmentUtilsTest.java
- if the provided tags are null or empty, and the gateway has exclusion tags, it will now return true
- if a tag is in the inclusion and exclusion lists, the method returns false.
---
- use it directly by updating your project with version: `3.3.1-improve-matching-tags-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/3.3.1-improve-matching-tags-SNAPSHOT/gravitee-common-3.3.1-improve-matching-tags-SNAPSHOT.zip)
=> fix: improving environment hasMatching feature

pom.xml, src/main/java/io/gravitee/common/templating/FreeMarkerComponent.java, src/test/java/io/gravitee/common/templating/FreeMarkerComponentTest.java, src/test/resources/freemarker/subpackage/template.ftl, src/test/resources/logback-test.xml
fix(freemarker): pass class loaders explicitely
This revision refactors the FreemarkerComponent to force passing a class loader explicitly when templates should be loaded from the class path.
---
- use it directly by updating your project with version: `3.3.1-fix-freemarker-component-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/3.3.1-fix-freemarker-component-SNAPSHOT/gravitee-common-3.3.1-fix-freemarker-component-SNAPSHOT.zip)
=> fix(freemarker): pass class loader explicitely

src/main/java/io/gravitee/common/security/CertificateUtils.java, src/test/java/io/gravitee/common/security/CertificateUtilsTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-2555
Not exactly related to the issue but allow to use encoded or non encoded certificate
---
- use it directly by updating your project with version: `3.3.1-apim-2555-allow-non-encoded-certificate-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/3.3.1-apim-2555-allow-non-encoded-certificate-SNAPSHOT/gravitee-common-3.3.1-apim-2555-allow-non-encoded-certificate-SNAPSHOT.zip)
=> fix: allow to extract non-encoded certificate

pom.xml, src/main/java/io/gravitee/common/cron/CronTrigger.java, src/main/java/io/gravitee/common/utils/TimeProvider.java, src/test/java/io/gravitee/common/cron/CronTriggerTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-3368
Introduce CronTrigger to share computation of Cron expression for nextExecutionTime across all products.
For testing facilities, We also introduce TimeProvider to be able to control the Clock from tests.
---
- use it directly by updating your project with version: `3.4.0-apim-3368-v4-dynamic-properties-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/3.4.0-apim-3368-v4-dynamic-properties-SNAPSHOT/gravitee-common-3.4.0-apim-3368-v4-dynamic-properties-SNAPSHOT.zip)
=> feat: introduce CronTrigger class

src/main/java/io/gravitee/common/utils/RxHelper.java, src/test/java/io/gravitee/common/utils/RxHelperTest.java
Add a predicate for expo retry backoff.
---
- use it directly by updating your project with version: `4.2.0-add-retry-expo-predicate-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/4.2.0-add-retry-expo-predicate-SNAPSHOT/gravitee-common-4.2.0-add-retry-expo-predicate-SNAPSHOT.zip)
=> feat: allow to filter retryable exception

pom.xml, src/main/java/io/gravitee/common/utils/SizeUtils.java, src/test/java/io/gravitee/common/utils/SizeUtilsTest.java
This is an extract of a conversion algorithm that can be found at several location in APIM (at least [here](https://github.com/gravitee-io/gravitee-api-management/blob/master/gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggingContext.java#L101) and [here](https://github.com/gravitee-io/gravitee-api-management/blob/master/gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/v4/analytics/LoggingContext.java#L106)).
This avoids duplication and facilitates reusability.
Once approved and merged, a PR will be opened on APIM.
---
- use it directly …
=> feat: add SizeUtils

pom.xml
Lombok should not be in scope `compile` but `provided`.
---
- use it directly by updating your project with version: `4.3.1-fix-remove-lombok-compile-dependency-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/4.3.1-fix-remove-lombok-compile-dependency-SNAPSHOT/gravitee-common-4.3.1-fix-remove-lombok-compile-dependency-SNAPSHOT.zip)
=> fix: make lombok dependency provided

pom.xml, src/main/java/io/gravitee/common/event/Event.java, src/main/java/io/gravitee/common/event/EventManager.java, src/main/java/io/gravitee/common/event/impl/EventManagerImpl.java, src/main/java/io/gravitee/common/event/impl/SimpleEvent.java, src/test/java/io/gravitee/common/event/SampleEvent.java, src/test/java/io/gravitee/common/event/SampleEventType.java, src/test/java/io/gravitee/common/event/impl/EventManagerImplTest.java
**Issue**
https://gravitee.atlassian.net/browse/CJ-1766
In order to properly unregister event listener when undeploying api, EventManager required some improvements:
- refactor EventManager to properly manage concurrency
- fix an issue when subscribing to subset of EventType
- add unsubscribe method to remove listener
---
- use it directly by updating your project with version: `4.4.0-CJ-1766-improve-event-manager-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/4.4.0-CJ-1766-improve-event-manager-SNAPSHOT/ …
=> feat: add unsubscribe method for EventManager

src/main/java/io/gravitee/common/data/domain/Page.java, src/main/java/io/gravitee/common/util/Maps.java
**Issue**
No issue associed
add map() method on page to allow usage as
```java
Page<B> result = service.findAllA().map(A::toB);
// instead of
Page<A> firstResult = service.findAllA();
var intermediate = firstResult.getContent().stream.map(A::toB);
Page<B> result = new Page<>(intermediate, firstResult.getPageNumber(), (int) firstResult.getPageElements(), firstResult.getTotalElements());;
```
=> imp(Page): add map() method to simplify usage

src/main/java/io/gravitee/common/util/TemplatedValueHashMap.java, src/test/java/io/gravitee/common/util/TemplatedValueHashMapTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-8819
This PR addresses an issue when using a Spring EL expression to access an API property with a key derived from an HTTP request header, such as `{#properties[#request.header['test']]}`. The problem arises because API properties are indexed by a string key, whereas HTTP headers are multi-valued, meaning `#request.header['test']` returns a list of string values.
In interpreted mode, Spring EL is able to detect that a string is expected and that a list of strings is provided, automatically extracting the first value. However, when the EL runs in compiled mode, used for performance optimization in V4 and V4 emulated mode, this behavior breaks completely. The reason it works in interpreted mode is …
=> fix: make get by list of string from EL

src/main/java/io/gravitee/common/utils/RxHelper.java, src/test/java/io/gravitee/common/utils/RxHelperTest.java
Rename `RxHelper.retry` for `RxHelper.retryCompletable`
Add a `retryLinear` that return the same type as `retryExponentialBackoff` so we can select the type of retry more easily
---
- use it directly by updating your project with version: `4.7.0-rxhelper-retry-rename-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/4.7.0-rxhelper-retry-rename-SNAPSHOT/gravitee-common-4.7.0-rxhelper-retry-rename-SNAPSHOT.zip)
=> feat: add retryLinear method

pom.xml
**Issue**
https://github.com/gravitee-io/issues/issues/11066
With reference to this PR : https://github.com/gravitee-io/gravitee-common/pull/147
CI/CD was failing for releasing new version, after approval and merge of #147.
link : https://app.circleci.com/pipelines/github/gravitee-io/gravitee-common/725/workflows/4750d18f-4480-4277-ad4a-599385976b58/jobs/3532
Got suggestion to update the  "gravitee-parent" version, which was not updated to the latest version. 
So updated the same in this PR
-------
Error :  Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.7.0:deploy failed: Nexus connection problem to URL [https://oss.sonatype.org/ ]: 401 - Unauthorized ->
----
#147 behaviour is working as expected
=> fix: gravitee-parent version update
