src/main/java/io/gravitee/common/data/domain/Order.java, src/main/java/io/gravitee/common/data/domain/Page.java
This closes gravitee-io/issues#113
=> feat(data.domain) : add Pagination and Order model

src/main/java/io/gravitee/common/utils/IdGenerator.java
This closes https://github.com/gravitee-io/issues/issues/112
=> Allows to group list of APIs by views

src/main/java/io/gravitee/common/node/AbstractNode.java
=> feat(policy): Do not start node when a component is not well started

src/main/java/io/gravitee/common/spring/factory/AbstractAutowiringFactoryBean.java
=> feat(gateway): Multi-tenant support

src/main/java/io/gravitee/common/http/HttpHeaders.java
=> feat(log): Request /response analysis

src/main/java/io/gravitee/common/util/LinkedMultiValueMap.java
=> fix(gateway): Update model to handle multiple values per query parameter

src/main/java/io/gravitee/common/spring/factory/AbstractAutowiringFactoryBean.java
=> feat(common): Add bean initialization

src/main/java/io/gravitee/common/util/LinkedCaseInsensitiveSet.java
=> feat: Add insensitive hash set

src/main/java/io/gravitee/common/http/HttpMethod.java
=> feat(http): Add code to HTTP method

src/main/java/io/gravitee/common/data/domain/MetadataPage.java
=> feat(audit): first implementation

src/main/java/io/gravitee/common/util/ChangeListener.java, src/main/java/io/gravitee/common/util/ObservableCollection.java, src/main/java/io/gravitee/common/util/ObservableSet.java
=> feat(collections): Add observable collections

pom.xml, src/main/java/io/gravitee/common/event/impl/EventManagerImpl.java
=> fix(health-check): Event listener must be ordered

src/main/java/io/gravitee/common/http/HttpMethod.java
Closes gravitee-io/issues#1193
=> fix(http): Add a specific enum value  to handle unknown HTTP Method

src/main/java/io/gravitee/common/util/RelaxedPropertySource.java, src/test/java/io/gravitee/common/util/RelaxedPropertySourceTest.java
=> feat(config): support different type of configuration

src/main/java/io/gravitee/common/util/EnvironmentUtils.java
Closes gravitee-io/issues#1278
=> chore: Move EnvironmentUtils from mgmt-api to common module

src/main/java/io/gravitee/common/node/Node.java
This closes gravitee-io/issues#1312
=> feat: display top paths/resources in analytics

src/main/java/io/gravitee/common/util/Maps.java
=> feat(api): Define response templates to override policy response

src/main/java/io/gravitee/common/http/MediaType.java
Required for coming PR about signed userinfo.
=> add media type for signed userinfo

src/main/java/io/gravitee/common/util/URIUtils.java, src/test/java/io/gravitee/common/util/URIUtilsTest.java
=> fix(requests): do not encode/decode query parameters by default

src/main/java/io/gravitee/common/http/MediaType.java
=> feat(mediatype): add event stream content-type

src/main/java/io/gravitee/common/utils/IdGenerator.java, src/test/java/io/gravitee/common/utils/IdGeneratorTest.java
Closes gravitee-io/issues#3176
=> feat(improve-idgen): Replace accented chars with regular chars

src/main/java/io/gravitee/common/http/HttpHeaders.java, src/main/java/io/gravitee/common/http/MediaType.java, src/test/java/io/gravitee/common/http/MediaTypeTest.java
Closes gravitee-io/issues#3212
=> fix(media): Parse and sort media types

src/main/java/io/gravitee/common/http/HttpHeaders.java
Add constant for X-Forwarded-Port header
Relates: gravitee-io/issues#3641
=> Added X-Forwarded-Port header

src/main/java/io/gravitee/common/util/LinkedCaseInsensitiveMap.java, src/test/java/io/gravitee/common/util/LinkedCaseInsensitiveMapTest.java
=> fix(LinkedCaseInsensitiveMap): implement the missing methods

src/main/java/io/gravitee/common/util/LinkedCaseInsensitiveMap.java, src/test/java/io/gravitee/common/util/LinkedCaseInsensitiveMapTest.java
=> chore: Merge 1.30.11

src/main/java/io/gravitee/common/http/IdGenerator.java, src/main/java/io/gravitee/common/utils/Hex.java, src/main/java/io/gravitee/common/utils/UUID.java
=> feat: Allows to pass a request id in outgoing headers

src/main/java/io/gravitee/common/http/HttpVersion.java, src/main/java/io/gravitee/common/http/MediaType.java
Closes gravitee-io/issues#3105
=> feat(grpc): Add GRPC support

src/main/java/io/gravitee/common/http/HttpHeaders.java
Fixes https://github.com/gravitee-io/issues/issues/4434
=> feat: forward x-forwarded-prefix to the backend endpoint

pom.xml, src/main/java/io/gravitee/common/util/EnvironmentUtils.java, src/test/java/io/gravitee/common/util/EnvironmentUtilsTest.java
Closes gravitee-io/issues#2680
=> fix(configuration): Merge properties based on key's format

src/main/java/io/gravitee/common/spring/factory/SpringFactoriesLoader.java
Closes gravitee-io/issues#5615
=> feat(optim): move spring factories logging level to debug

.circleci/config.yml, pom.xml, src/main/java/io/gravitee/common/util/EnvironmentUtils.java, src/test/java/io/gravitee/common/util/EnvironmentUtilsTest.java
=> feat: select gateway to execute debug request

pom.xml, src/main/java/io/gravitee/common/component/LifecycleComponent.java, src/main/java/io/gravitee/common/service/AbstractService.java
Closes gravitee-io/issues#5966
=> fix(event): propagate node stop event when shutdown

pom.xml, src/main/java/io/gravitee/common/http/HttpHeaders.java, src/main/java/io/gravitee/common/util/LinkedCaseInsensitiveMap.java, src/main/java/io/gravitee/common/util/LinkedMultiValueMap.java, src/main/java/io/gravitee/common/util/MultiValueMap.java, src/test/java/io/gravitee/common/http/HttpHeadersTest.java, src/test/java/io/gravitee/common/util/LinkedMultiValueMapTest.java
=> feat: create generate http signature policy

src/main/java/io/gravitee/common/util/LinkedCaseInsensitiveMultiValueMap.java, src/main/java/io/gravitee/common/util/LinkedMultiValueMap.java, src/test/java/io/gravitee/common/util/LinkedCaseInsensitiveMultiValueMapTest.java
=> feat: add a LinkedCaseInsensitiveMultiValueMap util class

pom.xml, src/main/java/io/gravitee/common/component/LifecycleComponent.java, src/main/java/io/gravitee/common/service/AbstractService.java
=> fix: node stop event not well propagated

src/main/java/io/gravitee/common/component/AbstractLifecycleComponent.java, src/main/java/io/gravitee/common/component/Lifecycle.java, src/main/java/io/gravitee/common/http/HttpHeadersValues.java
Closes gravitee-io/issues#6722
=> feat(graceful): add stopping status

pom.xml, src/main/java/io/gravitee/common/security/jwt/LazyJWT.java
Add LazyJWT so it can be reused wherever it make sense
=> feat(jupiter): mutualize LazyJWT for reusability

pom.xml, src/main/java/io/gravitee/common/utils/RxHelper.java, src/test/java/io/gravitee/common/utils/RxHelperTest.java
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-92
Add an rx helper to reuse some part of code and avoid duplicates.
=> feat: add RxHelper.mergeWithFirst method

src/main/java/io/gravitee/common/utils/RxHelper.java, src/test/java/io/gravitee/common/utils/RxHelperTest.java
**Issue**
Retry wasn't correctly deal with backpressure.
Retry was previously relying on interval operator which doesn't support backpressure. It means that once 1 exception occurred, the interval operator started to produce event each X time but, in the same time, no other exception occurred. After a certain amount of time, an error occurred.
The interval operator has been replaced with a simple delay applied on each element.
---
- use it directly by updating your project with version: `2.0.0-fix-retry-backpressure-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots …
=> fix: missing backpressure on retry

pom.xml, src/main/java/io/gravitee/common/utils/DurationParser.java, src/test/java/io/gravitee/common/utils/DurationParserTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-490
A small description of what you did in that PR.
=> APIM-490 add Duration parser 

pom.xml
**Issue**
N/A
Upgrade gravitee-bom
---
- use it directly by updating your project with version: `2.1.0-upgrade-bom-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/2.1.0-upgrade-bom-SNAPSHOT/gravitee-common-2.1.0-upgrade-bom-SNAPSHOT.zip)
=> Upgrade gravitee-bom

CHANGELOG.md, pom.xml, src/main/java/io/gravitee/common/util/URIUtils.java, src/main/java/io/gravitee/common/utils/DurationParser.java, src/main/java/io/gravitee/common/utils/RxHelper.java, src/test/java/io/gravitee/common/util/URIUtilsTest.java, src/test/java/io/gravitee/common/utils/DurationParserTest.java, src/test/java/io/gravitee/common/utils/RxHelperTest.java
=> Merge `alpha` into `master`

src/main/java/io/gravitee/common/data/domain/Page.java, src/test/java/io/gravitee/common/data/domain/PageTest.java
**Issue**
No issue associed
Fix the typing of my previous PR 🙏
---
- use it directly by updating your project with version: `4.5.1-page-improvement-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/4.5.1-page-improvement-SNAPSHOT/gravitee-common-4.5.1-page-improvement-SNAPSHOT.zip)
=> fix(Page): fix error in typing of map()

src/main/java/io/gravitee/common/utils/RxHelper.java, src/test/java/io/gravitee/common/utils/RxHelperTest.java
**Issue**
APIM-7412
Add max attempt retry backoff helper
---
- use it directly by updating your project with version: `4.6.0-apim-7412-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/4.6.0-apim-7412-SNAPSHOT/gravitee-common-4.6.0-apim-7412-SNAPSHOT.zip)
=> APIM-7412: Add max attempt retry backoff helper

src/main/java/io/gravitee/common/util/TemplatedValueHashMap.java, src/test/java/io/gravitee/common/util/TemplatedValueHashMapTest.java
https://github.com/gravitee-io/gravitee-common/pull/141
**Issue**
https://github.com/gravitee-io/issues/issues/XXXXX
A small description of what you did in that PR.
---
- use it directly by updating your project with version: `4.5.2-APIM-8819-attributes-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/common/gravitee-common/4.5.2-APIM-8819-attributes-SNAPSHOT/gravitee-common-4.5.2-APIM-8819-attributes-SNAPSHOT.zip)
=> fix: make get by list of string from EL
